# Generated by Django 4.1.5 on 2023-02-07 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='leader',
        ),
        migrations.DeleteModel(
            name='UrbanizationLeader',
        ),
    ]
