# Generated by Django 4.1.5 on 2023-02-09 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_urbanizationleader_contacts_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('type', models.CharField(choices=[('', '---------'), ('Vivienda', 'Vivienda'), ('Mejoramiento Vivienda', 'Mejoramiento Vivienda'), ('Universidad', 'Universidad'), ('Nivel 2 Hospital', 'Nivel 2 Hospital'), ('Credito para negocio', 'Credito para negocio')], max_length=30)),
                ('detail', models.TextField()),
                ('contact', models.TextField()),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.urbanizationleader')),
            ],
        ),
    ]
